name:                ICalendar
version:             0.1.0.0
license:             BSD3
author:              ""
maintainer:          ""
copyright:           ""

# extra-source-files:
# - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README

dependencies:
- array
- base >=4.14
- boxes
- containers
- uu-tc == 2015.1.1

library:
  source-dirs: src

executables:
  ICalendar-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ICalendar

#tests:
#  ICalendar-test:
#    main:                Spec.hs
#    source-dirs:         test
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - ICalendar
